name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: where-happened
    attributes:
      label: Where did the bug happen?
      description: Also tell us, how can we get there?
      placeholder: Tell us where this happened!
      value: "Home page"
    validations:
      required: true
  - type: textarea
    id: when-happened
    attributes:
      label: What triggered the bug?
      description: Tell us, what triggered the bug?
      placeholder: Tell us what triggered the bug!
      value: "The bug occured after I clicked the big red button."
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe the bug.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I got disconnected from my login session."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Relevant screenshots or videos
      description: Please take a screenshot of the problem, or record a `.gif`, and paste it here.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CONTRIBUTING.md](../CONTRIBUTING.md) file.
      options:
        - label: I agree to follow this project's `CONTRIBUTING.md` file.
          required: true
